apiVersion: v1
kind: Service
metadata:
  name: service-morra
  labels:
    app: morra
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30001
      protocol: TCP
  selector:
    app: morra
