apiVersion: v1
kind: Pod
metadata:
  name: pod-con-env-da-secret
spec:
  containers:
    - name: nome-container
      image: nome-immagine
      env:
        - name: NAME # nome della variabile d'ambiente
          valueFrom:
            secretKeyRef:
              name: esempio-secret # nome del secret
              key: nome # key del valore nel secret
        - name: KEY
          valueFrom:
            secretKeyRef:
              name: esempio-secret
              key: chiave
# risultato finale: le variabili d'ambiente seguenti:
# NAME=Carmine
# KEY=valore
