apiVersion: v1
kind: PersistentVolume
metadata:
  name: prova-pv-local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem # alternativa: Block per esporre partizioni e non FS
  accessModes:
    - ReadWriteOnce
  local:
    path: /percorso/in/host
  nodeAffinity: # specifica del nodo su cui va creato il PV
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname # selezione in base all'hostname
              operator: In
              values:
                - hostnamenodoconvolume # hostname del nodo
