version: "3.9"
services:
  app:
    build:
      context: .
    env_file:
      .env
    ports:
      - 8080:80
  db:
    image: mysql
    volumes:
      - testvol:/var/lib/mysql
    env_file:
      .env
volumes:
  testvol:

